# mysql 연결하기

FROM mysql

ENV MYSQL_USER=docker
ENV MYSQL_PASSWORD=docker123123
ENV MYSQL_ROOT_PASSWORD=root123123
ENV MYSQL_DATEBASE=dockerdb

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]